### ISSUE TITLE
[bug] Bad disk capacity detection in omni on baremetal servers

### ISSUE THREAD

**Issue by jpuyobro** [siderolabs/omni#1052]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Omni prints a wrong disk capacity (in my case 2 times the good size) because it takes into account /dev/dm-0 and /dev/dm-1.
Exemple : 
```
/dev/dm-0 10.00 GB UNKNOWN
/dev/dm-1 884.25 GB UNKNOWN
/dev/sda 894.25 GB SSD
```

This behaviour is observed either for machines in maintenance mode or machines in clusters.

When we see that for machine in maintenance mode, if the machine joins a cluster, it will be stuck rebooting forever (I guess this is the case because we don't use disk selector).

result of  `talosctl get discoveredvolumes -o yaml` :
```yaml
node: 4c4c4544-005a-5a10-8038-c4c04f4e3833
metadata:
    namespace: runtime
    type: DiscoveredVolumes.block.talos.dev
    id: dm-0
    version: 1
    owner: block.DiscoveryController
    phase: running
    created: 2025-03-31T12:34:07Z
    updated: 2025-03-31T12:34:07Z
spec:
    dev_dath: /dev/dm-0
    type: disk
    device_path: /sys/devices/virtual/block/dm-0
    size: 10737418240
    pretty_size: 11 GB
    sector_size: 512
    io_size: 4096
    name: ext4
    uuid: 0bfa1f7b-1429-4be7-939d-00b5074d64d9
    label: rootlvm_partdisk
    block_size: 4096
    filesystem_block_size: 4096
    probed_size: 10737418240
---
node: 4c4c4544-005a-5a10-8038-c4c04f4e3833
metadata:
    namespace: runtime
    type: DiscoveredVolumes.block.talos.dev
    id: dm-1
    version: 1
    owner: block.DiscoveryController
    phase: running
    created: 2025-03-31T12:34:07Z
    updated: 2025-03-31T12:34:07Z
spec:
    dev_dath: /dev/dm-1
    type: disk
    device_path: /sys/devices/virtual/block/dm-1
    size: 949452013568
    pretty_size: 950 GB
    sector_size: 512
    io_size: 4096
    name: ext4
    uuid: d546f733-4840-4718-bb43-c869c81f88d9
    label: rootlvm_partdisk
    block_size: 4096
    filesystem_block_size: 4096
    probed_size: 949452013568
---
node: 4c4c4544-005a-5a10-8038-c4c04f4e3833
metadata:
    namespace: runtime
    type: DiscoveredVolumes.block.talos.dev
    id: loop3
    version: 1
    owner: block.DiscoveryController
    phase: running
    created: 2025-03-31T12:34:06Z
    updated: 2025-03-31T12:34:06Z
spec:
    dev_dath: /dev/loop3
    type: disk
    device_path: /sys/devices/virtual/block/loop3
    size: 73695232
    pretty_size: 74 MB
    sector_size: 512
    io_size: 512
    name: squashfs
    block_size: 131072
    filesystem_block_size: 131072
    probed_size: 73691838
---
node: 4c4c4544-005a-5a10-8038-c4c04f4e3833
metadata:
    namespace: runtime
    type: DiscoveredVolumes.block.talos.dev
    id: sda
    version: 1
    owner: block.DiscoveryController
    phase: running
    created: 2025-03-31T12:34:07Z
    updated: 2025-03-31T12:34:07Z
spec:
    dev_dath: /dev/sda
    type: disk
    device_path: /sys/devices/pci0000:00/0000:00:17.0/ata1/host0/target0:0:0/0:0:0:0/block/sda
    size: 960197124096
    pretty_size: 960 GB
    sector_size: 512
    io_size: 4096
    name: gpt
    uuid: 9f913ea2-5ac8-4503-a400-d64fc49ec7c6
    block_size: 512
    probed_size: 960197089792
---
node: 4c4c4544-005a-5a10-8038-c4c04f4e3833
metadata:
    namespace: runtime
    type: DiscoveredVolumes.block.talos.dev
    id: sda1
    version: 1
    owner: block.DiscoveryController
    phase: running
    created: 2025-03-31T12:34:07Z
    updated: 2025-03-31T12:34:07Z
spec:
    dev_dath: /dev/sda1
    type: partition
    device_path: /sys/devices/pci0000:00/0000:00:17.0/ata1/host0/target0:0:0/0:0:0:0/block/sda/sda1
    parent: sda
    parent_dev_path: /dev/sda
    size: 1048576
    pretty_size: 1.0 MB
    sector_size: 512
    io_size: 4096
    name: ""
    partition_uuid: fe5e6b28-ffbe-4b68-a6ed-dd36aa60ee7f
    partition_type: 21686148-6449-6e6f-744e-656564454649
    partition_index: 1
---
node: 4c4c4544-005a-5a10-8038-c4c04f4e3833
metadata:
    namespace: runtime
    type: DiscoveredVolumes.block.talos.dev
    id: sda2
    version: 1
    owner: block.DiscoveryController
    phase: running
    created: 2025-03-31T12:34:07Z
    updated: 2025-03-31T12:34:07Z
spec:
    dev_dath: /dev/sda2
    type: partition
    device_path: /sys/devices/pci0000:00/0000:00:17.0/ata1/host0/target0:0:0/0:0:0:0/block/sda/sda2
    parent: sda
    parent_dev_path: /dev/sda
    size: 960193626112
    pretty_size: 960 GB
    sector_size: 512
    io_size: 4096
    name: lvm2-pv
    label: TtWCL3-xK2p-h2YQ-guq2-D7Uz-tLBy-xbaAOZ
    partition_uuid: ab1940e1-7b54-49a5-9f27-70fb881141b6
    partition_type: 0fc63daf-8483-4772-8e79-3d69d8477de4
    partition_index: 2
```

### Expected Behavior

I should see only the real disks present on the machine: 
in my example: 
`/dev/sda 894.25 GB SSD`

result of  `talosctl get discoveredvolumes -o yaml`:
```yaml
node: 4c4c4544-005a-3710-8047-c4c04f4e3833
metadata:
    namespace: runtime
    type: DiscoveredVolumes.block.talos.dev
    id: loop3
    version: 1
    owner: block.DiscoveryController
    phase: running
    created: 2025-03-31T13:59:43Z
    updated: 2025-03-31T13:59:43Z
spec:
    dev_dath: /dev/loop3
    type: disk
    device_path: /sys/devices/virtual/block/loop3
    size: 73695232
    pretty_size: 74 MB
    sector_size: 512
    io_size: 512
    name: squashfs
    block_size: 131072
    filesystem_block_size: 131072
    probed_size: 73691838
---
node: 4c4c4544-005a-3710-8047-c4c04f4e3833
metadata:
    namespace: runtime
    type: DiscoveredVolumes.block.talos.dev
    id: sda
    version: 1
    owner: block.DiscoveryController
    phase: running
    created: 2025-03-31T13:59:43Z
    updated: 2025-03-31T13:59:43Z
spec:
    dev_dath: /dev/sda
    type: disk
    device_path: /sys/devices/pci0000:00/0000:00:17.0/ata1/host0/target0:0:0/0:0:0:0/block/sda
    size: 960197124096
    pretty_size: 960 GB
    sector_size: 512
    io_size: 4096
    name: ""

```

### Steps To Reproduce

Take a bare metal machine that hasn't been correctly wiped that used to have a talos linux installed with disk encryption. Boot the machine on talos with the good args to make it join your omni instance on PXE.

You should see a wrong disk size and some /dev/dm-* volumes.

Or take a baremetal server and make it join a cluster where disk encryption is enabled. The disk size will be wrong when the machine is up and ready.
