### ISSUE TITLE
[feature] Support multiple `EtcdBackupS3Configs`

### ISSUE THREAD

**Issue by TimJones** [siderolabs/omni#1144]
### Problem Description

For improved SOC-II compliance and generate separation of concerns it is necessary to be able to define separate destinations and/or credentials for Etcd backups.

### Solution

Omni to support multiple `EtcdBackupS3Config` resources and assign them to each cluster.

The cluster template should also be enhanced to support it, something like the following:

```yaml
kind: Cluster
name: talos-default
kubernetes:
  version: v1.28.2
talos:
  version: v1.5.5
features:
  backupConfiguration:
    id: <id-of-existing-EtcdBackupS3Config>
    interval: 1h
```

### Alternative Solutions

A workaround is using the Talos in-cluster-API-ServiceAccount and a CronJob to do the same.

### Notes

I would say that if there is no `id` in the `backupConfiguration` and only one `EtcdBackupS3Config` defined then it's fine to associate it implicitly as Omni does now.
