### ISSUE TITLE
[bug] UserVolumeConfig is not supported

### ISSUE THREAD

**Issue by Simon-Boyer** [siderolabs/omni#1196]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Adding a config patch to a cluster or machine to apply a UserVolumeConfig results in the following error:
`1 error occurred: * "UserVolumeConfig" "v1alpha1": not registered`

### Expected Behavior

The UserVolumeConfig is correctly applied

### Steps To Reproduce

1. In an SaaS omni environment
2. Applying an UserVolumeConfig patch. In my case it was targetting all worker nodes of a cluster and the patch is as follow:
```yaml
apiVersion: v1alpha1
kind: UserVolumeConfig
name: local-path-provisioner
provisioning:
  diskSelector:
    match: disk.size > 120u * GB
  minSize: 10GB
  maxSize: 100GB
```
