### ISSUE TITLE
[bug] machines do not come back after deleting them (bm provider)

### ISSUE THREAD

**Issue by killcity** [siderolabs/omni#1238]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

I had created a cluster with a couple machines that were "configuring". I then deleted the cluster and then destroyed the cluster and then the machines. I've done this before and they were OK. 

Console on the nodes that aren't sitting at "Pending" show:

```
[ 1111.133224] [talos] controller failed ("component": "controller-runtime", "controller": "u1alpha1.EventsSinkController", "error": "error publishing event: rp
code = Unknown desc = no machines found for address fdae:41e4:649b:9303
```

### Expected Behavior

I expected the machines to attempt to re-register so they would appear under "Pending".

### Steps To Reproduce

1. add machines
2. create cluster
3. delete cluster
4. delete machines
5. delete infraprovider
6. create new infraprovider and use new key to redeploy bm-provisioner docker container
7. try to add machines

### What browsers are you seeing the problem on?

Safari

### Anything else?

Seems this happened after cleaning out my infra providers, creating a fresh new one and then trying to bring the machines back in.

Newly added machines that never were enrolled previously in Omni do not have this problem.

**Comment by Unix4ever** [comment]
Manually rebooting the machine might help to make them appear.
cc @utkuozdemir

**Comment by killcity** [comment]
Did do that to no avail. Also reboot and used ISO with reset option and still nothing.

**Comment by utkuozdemir** [comment]
Can you please check the output of `omnictl get links` and delete if there is any of them by doing `omnictl delete link`?

Also please check the output of `omnictl get inframachine`. I suspect the deletion/cleanup of the old ones were not completed successfully.

**Comment by killcity** [comment]
Ding Ding! I see both nodes listed under the two commands you gave me. Is there a way to make this more obvious in the UI? Going to try and delete them now. I will report back what I find.

**Comment by killcity** [comment]
I was able to delete both `links`, but the deletion of the `infraproviders` hung for both.

**Comment by killcity** [comment]
Actually,  after deleting the `links`, the nodes re-appeared in `links`, but they are now appearing in the ui.

**Comment by utkuozdemir** [comment]
We probably need to do something to make the links deletable from the UI as well. If I recall correctly, this was the case back then when you deleted a machine from the machines screen, but then we changed it.

**Comment by killcity** [comment]
So I deleted the `links` and saw them come back in and still saw the original tags (didnt show up in pending - just straight back into the machine list). I tried to delete them again and then also delete the `inframachine` counterparts, but they just both hang when I run the command.

**Comment by utkuozdemir** [comment]
The reason they don't go back to pending is because the `InfraMachineConfig` resources were still there, and they contain the acceptance status of those machines.

Normally, those resources are cleaned up when the corresponding `Machine` resource is removed, but I think in your case, when you delete the links, the `Machine` resources still remain. I think this is because the provider is gone, so their cleanup cannot be completed.

Deleting `inframachine` resources manually will never work, since they are not user-owned resources. It hanging is actually misleading, we should fail there explicitly. It hangs because those resources are already in `tearingDown` phase, waiting for their finalizers to be completed and removed. Same as above, their cleanup can never be completed.

Can you check some of the `Machine` and `InfraMachine` resources with `-oyaml`, and see their `.metadata.phase` and their `.metadata.finalizers`? I believe the issue is, because the infra provider which managed those machines are now gone, they are in a non-finalizeable state.

Is your infra provider running meanwhile? And are you using the same provider ID as the original one (did you recreate it with the same id?)

**Comment by killcity** [comment]
Here is the output for the phase and finalizers for one of the misbehaving nodes. Now I did change the provisioner id after i deleted these. I wanted to clean things up, so it seems like maybe due to the original provisioner id not be there anymore - it’s now in some weird state?

```
metadata:
    namespace: infra-provider
    type: InfraMachines.omni.sidero.dev
    id: 0016fc56-3615-ea11-906e-0017a4403562
    version: 12
    owner: InfraMachineController
    phase: tearingDown
    created: 2025-06-01T04:59:27Z
    updated: 2025-06-02T15:42:05Z
    labels:
        omni.sidero.dev/infra-provider-id: BareMetal-IAD1
    finalizers:
        - BareMetal-IAD1.RebootStatusController
        - BareMetal-IAD1.InfraMachineStatusController
        - BareMetal-IAD1.BMCConfigurationController
        - BareMetal-IAD1.WipeStatusController
        - BareMetal-IAD1.MachineStatusController
        - BareMetal-IAD1.PowerOperationController
spec:
    preferredpowerstate: 0
    acceptancestatus: 1
    clustertalosversion: 1.9.6
    extensions:
        - siderolabs/iscsi-tools
        - siderolabs/util-linux-tools
        - siderolabs/intel-ucode
    wipeid: ""
    extrakernelargs: ""
    requestedrebootid: ""
    cordoned: false
    installeventid: 0
    nodeuniquetoken: “"
```
