### ISSUE TITLE
[bug] Omni v0.33.0-beta.0 does not start

### ISSUE THREAD

**Issue by kenlasko** [siderolabs/omni#141]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Testing out Omni v0.33.0-beta.0 in my homelab and it does not start, where v0.32.2 works fine.

Error logs:
```
INF backend/server.go:913 > ts=1713016698.0266688 msg=internal API server starting component=server address=gateway-conn
INF backend/server.go:835 > ts=1713016698.0271397 msg=server starting component=server server=0.0.0.0:4443 server_type=api
INF backend/server.go:835 > ts=1713016698.0287764 msg=server starting component=server server=0.0.0.0:2122 server_type=metrics
INF backend/server.go:835 > ts=1713016698.0295844 msg=server starting component=server server=0.0.0.0:8100 server_type=k8s_proxy
INF backend/server.go:900 > ts=1713016698.029028 msg=starting local resource server component=server
INF backend/server.go:913 > ts=1713016698.029108 msg=internal API server starting component=server address=grpc-conn
INF backend/proxy_server.go:90 > ts=1713016698.0291185 msg=proxy server disabled component=server reason=bind address is empty
INF siderolink/loghandler.go:58 > ts=1713016698.029151 msg=starting log handler component=siderolink_log_handler
INF siderolink/manager.go:616 > ts=1713016698.0347006 msg=add this kernel argument to a Talos instance you would like to connect: siderolink.api=https://omni.mydomain.com:8090/?jointoken=<redacted> talos.events.sink=[fdae:41e4:649b:9303::1]:8091 talos.logging.kernel=tcp://[fdae:41e4:649b:9303::1]:8092 component=siderolink
INF wireguard/wireguard.go:126 > ts=1713016698.0363793 msg=attempting to configure tun device (userspace) component=siderolink serverPrefix=fdae:41e4:649b:9303::1/64
INF siderolink/loghandler.go:89 > ts=1713016698.036979 msg=save all log buffers before shutdown component=siderolink_log_handler storage_path=_out/logs
INF backend/server.go:928 > ts=1713016698.0371265 msg=grpc server stopping component=server
INF backend/server.go:850 > ts=1713016698.0371597 msg=server stopping component=server server=0.0.0.0:8100 server_type=k8s_proxy
INF backend/server.go:862 > ts=1713016698.0383317 msg=server stopped component=server server=0.0.0.0:8100 server_type=k8s_proxy
INF qruntime/qruntime.go:284 > ts=1713016698.0386896 msg=reconcile succeeded component=omni_runtime controller=TalosExtensionsController namespace=default type=TalosVersions.omni.sidero.dev id=1.3.6 job=reconcile busy=0.01670294
INF backend/server.go:850 > ts=1713016698.0371776 msg=server stopping component=server server=0.0.0.0:2122 server_type=metrics
INF backend/server.go:850 > ts=1713016698.0371914 msg=server stopping component=server server=0.0.0.0:4443 server_type=api
INF backend/server.go:862 > ts=1713016698.0391424 msg=server stopped component=server server=0.0.0.0:2122 server_type=metrics
INF backend/server.go:928 > ts=1713016698.0372062 msg=grpc server stopping component=server
INF backend/server.go:934 > ts=1713016698.0378985 msg=internal API server stopped component=server
INF backend/server.go:934 > ts=1713016698.0392802 msg=internal API server stopped component=server
INF backend/server.go:862 > ts=1713016698.0393295 msg=server stopped component=server server=0.0.0.0:4443 server_type=api
INF omni/state_etcd_election.go:75 > ts=1713016698.0432253 msg=resigned from the etcd election campaign component=elections
INF embed/etcd.go:375 > ts=1713016698.0563712 msg=closing etcd server component=embedded_etcd name=default data-dir=_out/etcd/ advertise-peer-urls=["http://localhost:2380"] advertise-client-urls=["http://localhost:2379"]
WRN embed/serve.go:160 > ts=1713016698.05662 msg=stopping insecure grpc server due to error component=embedded_etcd error=accept tcp 127.0.0.1:2379: use of closed network connection
WRN embed/serve.go:162 > ts=1713016698.0567236 msg=stopped insecure grpc server due to error component=embedded_etcd error=accept tcp 127.0.0.1:2379: use of closed network connection
INF etcdserver/server.go:1471 > ts=1713016698.0568612 msg=skipped leadership transfer for single voting member cluster component=embedded_etcd local-member-id=8e9e05c52164694d current-leader-member-id=8e9e05c52164694d
INF embed/etcd.go:579 > ts=1713016698.069604 msg=stopping serving peer traffic component=embedded_etcd address=127.0.0.1:44085
INF embed/etcd.go:584 > ts=1713016698.070175 msg=stopped serving peer traffic component=embedded_etcd address=127.0.0.1:44085
INF embed/etcd.go:377 > ts=1713016698.0702324 msg=closed etcd server component=embedded_etcd name=default data-dir=_out/etcd/ advertise-peer-urls=["http://localhost:2380"] advertise-client-urls=["http://localhost:2379"]
Error: failed to run Omni: failed to run server: error initializing wgDevice: error creating tun device: CreateTUN("siderolink") failed; /dev/net/tun does not exist
```

### Expected Behavior

Should start without error

### Steps To Reproduce

Hardware: RPi4b
Kernel: 6.1.21-v8+
Docker: 26.0.1

docker-compose.yaml
```
  omni:
    image: ghcr.io/siderolabs/omni:v0.33.0-beta.0  #v0.32.0  #v0.33.0-beta.0
    container_name: omni
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
    command:
      - --account-id=<redacted>
      - --name=onprem-omni
      - --cert=/tls.crt
      - --key=/tls.key
      - --siderolink-api-cert=/tls.crt
      - --siderolink-api-key=/tls.key
      - --private-key-source=file:///omni.asc
      - --event-sink-port=8091
      - --bind-addr=0.0.0.0:4443
      - --siderolink-api-bind-addr=0.0.0.0:8090
      - --k8s-proxy-bind-addr=0.0.0.0:8100
      - --advertised-api-url=https://omni.mydomain.com/
      - --siderolink-api-advertised-url=https://omni.mydomain.com:8090/
      - --siderolink-wireguard-advertised-addr=192.168.1.17:50180
      - --advertised-kubernetes-proxy-url=https://omni.mydomain.com:8100/
      - --auth-auth0-enabled=true
      - --auth-auth0-domain=mydomain.us.auth0.com
      - --auth-auth0-client-id=<redacted>
      - --initial-users=<myemailaddress>
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.omni.rule=Host(`omni.mydomain.com`)"
      - "traefik.http.routers.omni.entrypoints=websecure"
      - "traefik.http.routers.omni.tls=true"
      - "traefik.http.services.omni.loadbalancer.server.port=4443"
      - "traefik.http.services.omni.loadbalancer.server.scheme=https"
    volumes:
      - ./omni/etcd:/_out/etcd
      - ./certs/star_mydomain_com.pem:/tls.crt
      - ./certs/star_mydomain_com.key:/tls.key
      - ./omni/omni.asc:/omni.asc
```

### What browsers are you seeing the problem on?

Chrome
