### ISSUE TITLE
[feature] Resync bootstrap manifests

### ISSUE THREAD

**Issue by neilmfrench** [siderolabs/omni#290]
### Problem Description

Currently, the Bootstrap Manifest Sync page does not offer a way to re-compile the desired manifests on request. For example, if I have a custom CNI:
```yaml
cluster:
    cni:
      name: custom
      urls:
        - https://raw.githubusercontent.com/.../install.yaml
```
and I change something in https://raw.githubusercontent.com/.../install.yaml for the CNI and cluster itself, those changes won't be reflected in what the Bootstrap Manifest Sync page is using to compare against actual cluster state. This results in a situation where the page is telling me I have manifests out of sync but I know they actually aren't.

### Solution

Add a resync button that re-pulls all external sources.
