### ISSUE TITLE
Specifying schematic in a cluster template

### ISSUE THREAD

**Issue by smira** [siderolabs/omni#45]
```yaml
Machine:
   systemExtensions:
       -tailscale
       - zfs
...
Cluster:
   systemExtensions:
       -tailscale
       - zfs
...
MachineSet (ControlPlane/Workers):
   systemExtensions:
       - zfs
```  

(systemExtensions are not merged, they override each other)

`systemExtensions` is mapped to schematic ID, and `SchematicConfiguration` with proper labels is generated.
