### ISSUE TITLE
[bug] ClusterStatus machines count is wrong

### ISSUE THREAD

**Issue by vbehar** [siderolabs/omni#609]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The count of connected and requested machines in the ClusterStatus are 0, but in the MachineSetStatus they are good.

output of `omnictl get clusterstatus foo -o yaml`:

```
spec:
    available: true
    machines:
        total: 40
        healthy: 40
        connected: 0
        requested: 0
```

and output of `omnictl get machinesetstatus foo-bar -o yaml`:

```
spec:
    phase: 3
    ready: true
    error: ""
    machines:
        total: 32
        healthy: 32
        connected: 32
        requested: 32
```

### Expected Behavior

output of `omnictl get clusterstatus foo -o yaml`:

```
spec:
    available: true
    machines:
        total: 40
        healthy: 40
        connected: 40
        requested: 40
```

### Steps To Reproduce

1. create a cluster with a machineset
2. run `omnictl get clusterstatus CLUSTER_NAME -o yaml` - see that the connected and requested machines are set to 0
3. run `omnictl get machinesetstatus MACHINE_SET_NAME -o yaml` - see that the connected and requested machines is not 0

### Anything else?

this was created as https://github.com/siderolabs/omni-feedback/issues/72 - I'm just moving it here
