### ISSUE TITLE
[bug] cluster deploying but kube api never becomes available

### ISSUE THREAD

**Issue by Jubblin** [siderolabs/omni#642]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Deploying cluster using local instance of omni, cluster is configured as expected with no errors however the kube API never becomes available.

Output in logs says [talos] kubernetes endpoint watch error {"component": "controller-runtime", "controller": "k8s.EndpointController", "error": "failed to list *v1.Endpoints: Get \"https://[xxxx:xxxx:xxxx:xxxx::1]:10000/api/v1/namespaces/default/endpoints?fieldSelector=metadata.name%3Dkubernetes&limit=500&resourceVersion=0\": http: server gave HTTP response to HTTPS client"} 

### Expected Behavior

kube api becomes available in ui and kubectl is able to manage

### Steps To Reproduce

Omni running on docker container, create cluster using web UI wait for cluster to deploy

### Anything else?

[support.zip](https://github.com/user-attachments/files/17060067/support.zip)
support zip attached as requested by Andrey Smirnov

**Comment by Unix4ever** [comment]
I assume it may be something related to how you run Omni.
If you use a reverse proxy, I'd check what happens if you try to reach <omni-endpoint>:10000:
```bash
curl http://<omni-endpoint>:10000
curl https://<omni-endpoint>:10000
```

For my Omni running in docker with host networking I see this:
```yaml
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
}
```
