### ISSUE TITLE
[bug] Lost configuration after upgrade to v1.8.1

### ISSUE THREAD

**Issue by erickuiper** [siderolabs/omni#715]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We have a device that was running on 1.7.6, but after the upgrade it lost all its configuration. The reboot was triggered but it never came back online. Initially I thought there was an issue with the config patches as it complained about DHCP not being able to discover an IP for an interface that has a static IP configured.

I re-applied the patch with the machine.network.interfaces config, after the reboot I got a notification that the system is not bootstrapped.

### Expected Behavior

Upgrade will keep the existing config and come back online with the new version.

### Steps To Reproduce

A deployment Talos Linux on a KVM based hypervisor with three network interfaces running on v1.7.6 with the following config patches:
```
machine:
    network:
        interfaces:
            - addresses:
                - <masked>/24
              deviceSelector:
                hardwareAddr: <masked>
            - addresses: # internal network
                - <internal network>/24
              deviceSelector:
                hardwareAddr: <masked>
cluster:
    apiServer:
        admissionControl:
            - name: PodSecurity
              configuration:
                exemptions:
                    namespaces:
                        - <additional namespace>
  kubelet:
    nodeIP:
      validSubnets:
        - <internal network>/24
cluster:
  etcd:
    advertisedSubnets:
      - <internal network>/24
```
Triggered the upgrade and ended up in a failed state.

### What browsers are you seeing the problem on?

Chrome

### Anything else?

Support bundle is available on request
