### ISSUE TITLE
[bug] node not appearing in machines, not usable

### ISSUE THREAD

**Issue by thecodeassassin** [siderolabs/omni#81]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There is one node (out of 3) that first appeared in "Machines"  but now only shows up when creating a new cluster. 

Nodes (cluster creation)
https://tca0.nl/AzY

Nodes (machines)
https://tca0.nl/Lwm

What I did was I removed the machine via the UI, after that it refused to show up again.

### Expected Behavior

All 3 nodes available for use. Or would love to remove the node to be able to re-add it

### Steps To Reproduce

1. Add machine
2. Remove the machine via UI
3. Restart machine
4. Go to machines

**Comment by thecodeassassin** [comment]
One thing worth mentioning is that reformatting the node with kernel parameters to join a different omni account works flawlessly:

https://tca0.nl/NGs

**Comment by thecodeassassin** [comment]
@Unix4ever 

```
metadata:
    namespace: default
    type: MachineStatuses.omni.sidero.dev
    id: 30313939-6432-3866-3661-373136306465
    version: 12
    owner: MachineStatusController
    phase: running
    created: 2024-03-19T16:09:02Z
    updated: 2024-03-19T20:15:16Z
    labels:
        omni.sidero.dev/arch: arm64
        omni.sidero.dev/available:
        omni.sidero.dev/connected:
        omni.sidero.dev/net: 1Gbps
        omni.sidero.dev/platform: metal
        omni.sidero.dev/reporting-events:
        omni.sidero.dev/storage: 1031GB
    finalizers:
        - MachineConfigGenOptionsController
spec:
    talosversion: v1.6.3
    hardware:
        processors: []
        memorymodules: []
        blockdevices:
            - size: 31268536320
              model: ""
              linuxname: /dev/mmcblk0
              name: BJTD4R
              serial: "0x5ab3e80d"
              uuid: ""
              wwid: ""
              type: SD
              buspath: /platform/fe2e0000.mmc/mmc_host/mmc0/mmc0:0001/
              systemdisk: true
            - size: 4194304
              model: ""
              linuxname: /dev/mmcblk0boot0
              name: ""
              serial: ""
              uuid: ""
              wwid: ""
              type: SD
              buspath: /platform/fe2e0000.mmc/mmc_host/mmc0/mmc0:0001/block/mmcblk0/mmcblk0boot0
              systemdisk: false
            - size: 4194304
              model: ""
              linuxname: /dev/mmcblk0boot1
              name: ""
              serial: ""
              uuid: ""
              wwid: ""
              type: SD
              buspath: /platform/fe2e0000.mmc/mmc_host/mmc0/mmc0:0001/block/mmcblk0/mmcblk0boot1
              systemdisk: false
            - size: 1000204886016
              model: Samsung SSD 980 1TB
              linuxname: /dev/nvme0n1
              name: ""
              serial: S649NF0R827437X
              uuid: ""
              wwid: eui.002538d811b1593b
              type: NVME
              buspath: /platform/a40000000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/nvme/nvme0/nvme0n1
              systemdisk: false
        arch: arm64
    network:
        hostname: talos-8xs-u6q
        domainname: ""
        addresses:
            - 10.10.10.65/24
        defaultgateways:
            - 10.10.10.1
        networklinks:
            - linuxname: enx22c9d4e48ca1
              hardwareaddress: 22:c9:d4:e4:8c:a1
              speedmbps: 1000
              linkup: true
              description: ' '
    lasterror: ""
    managementaddress: fdae:41e4:649b:9303:fcdd:cc3b:ffcf:2349
    connected: true
    maintenance: true
    cluster: ""
    role: 0
    platformmetadata:
        platform: metal
        hostname: ""
        region: ""
        zone: ""
        instancetype: ""
        instanceid: 30313939-6432-3866-3661-373136306465
        providerid: ""
        spot: false
    imagelabels: {}
    schematic:
        id: ""
        invalid: true
---
metadata:
    namespace: default
    type: MachineStatuses.omni.sidero.dev
    id: 62303433-3839-3263-3834-373836633336
    version: 12
    owner: MachineStatusController
    phase: tearingDown
    created: 2024-03-19T11:53:01Z
    updated: 2024-03-19T16:07:47Z
    labels:
        location: node1
        omni.sidero.dev/arch: arm64
        omni.sidero.dev/available:
        omni.sidero.dev/connected:
        omni.sidero.dev/net: 1Gbps
        omni.sidero.dev/platform: metal
        omni.sidero.dev/reporting-events:
        omni.sidero.dev/storage: 531GB
        role: master
spec:
    talosversion: v1.6.3
    hardware:
        processors: []
        memorymodules: []
        blockdevices:
            - size: 31268536320
              model: ""
              linuxname: /dev/mmcblk0
              name: BJTD4R
              serial: "0x5edee801"
              uuid: ""
              wwid: ""
              type: SD
              buspath: /platform/fe2e0000.mmc/mmc_host/mmc0/mmc0:0001/
              systemdisk: true
            - size: 4194304
              model: ""
              linuxname: /dev/mmcblk0boot0
              name: ""
              serial: ""
              uuid: ""
              wwid: ""
              type: SD
              buspath: /platform/fe2e0000.mmc/mmc_host/mmc0/mmc0:0001/block/mmcblk0/mmcblk0boot0
              systemdisk: false
            - size: 4194304
              model: ""
              linuxname: /dev/mmcblk0boot1
              name: ""
              serial: ""
              uuid: ""
              wwid: ""
              type: SD
              buspath: /platform/fe2e0000.mmc/mmc_host/mmc0/mmc0:0001/block/mmcblk0/mmcblk0boot1
              systemdisk: false
            - size: 500107862016
              model: Samsung SSD 970 EVO Plus 500GB
              linuxname: /dev/nvme0n1
              name: ""
              serial: S4EVNX0T139542Z
              uuid: ""
              wwid: eui.0025385121b0d6b7
              type: NVME
              buspath: /platform/a40000000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/nvme/nvme0/nvme0n1
              systemdisk: false
        arch: arm64
    network:
        hostname: ""
        domainname: ""
        addresses:
            - 10.10.10.64/24
        defaultgateways:
            - 10.10.10.1
        networklinks:
            - linuxname: enxd288e0fd9d37
              hardwareaddress: d2:88:e0:fd:9d:37
              speedmbps: 1000
              linkup: true
              description: ' '
    lasterror: ""
    managementaddress: fdae:41e4:649b:9303:ea68:cea9:587f:3c98
    connected: true
    maintenance: true
    cluster: ""
    role: 0
    platformmetadata:
        platform: metal
        hostname: ""
        region: ""
        zone: ""
        instancetype: ""
        instanceid: 62303433-3839-3263-3834-373836633336
        providerid: ""
        spot: false
    imagelabels: {}
    schematic:
        id: ""
        invalid: true
---
metadata:
    namespace: default
    type: MachineStatuses.omni.sidero.dev
    id: 65653663-3339-6565-6134-663032613261
    version: 10
    owner: MachineStatusController
    phase: running
    created: 2024-03-19T16:09:08Z
    updated: 2024-03-19T20:15:15Z
    labels:
        omni.sidero.dev/arch: arm64
        omni.sidero.dev/available:
        omni.sidero.dev/connected:
        omni.sidero.dev/net: 1Gbps
        omni.sidero.dev/platform: metal
        omni.sidero.dev/reporting-events:
        omni.sidero.dev/storage: 1031GB
    finalizers:
        - MachineConfigGenOptionsController
spec:
    talosversion: v1.6.3
    hardware:
        processors: []
        memorymodules: []
        blockdevices:
            - size: 31268536320
              model: ""
              linuxname: /dev/mmcblk0
              name: BJTD4R
              serial: "0x5aaae8a6"
              uuid: ""
              wwid: ""
              type: SD
              buspath: /platform/fe2e0000.mmc/mmc_host/mmc0/mmc0:0001/
              systemdisk: true
            - size: 4194304
              model: ""
              linuxname: /dev/mmcblk0boot0
              name: ""
              serial: ""
              uuid: ""
              wwid: ""
              type: SD
              buspath: /platform/fe2e0000.mmc/mmc_host/mmc0/mmc0:0001/block/mmcblk0/mmcblk0boot0
              systemdisk: false
            - size: 4194304
              model: ""
              linuxname: /dev/mmcblk0boot1
              name: ""
              serial: ""
              uuid: ""
              wwid: ""
              type: SD
              buspath: /platform/fe2e0000.mmc/mmc_host/mmc0/mmc0:0001/block/mmcblk0/mmcblk0boot1
              systemdisk: false
            - size: 1000204886016
              model: Samsung SSD 980 1TB
              linuxname: /dev/nvme0n1
              name: ""
              serial: S649NJ0R221787D
              uuid: ""
              wwid: eui.002538d211405686
              type: NVME
              buspath: /platform/a40000000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/nvme/nvme0/nvme0n1
              systemdisk: false
        arch: arm64
    network:
        hostname: talos-4sg-l2p
        domainname: ""
        addresses:
            - 10.10.10.66/24
        defaultgateways:
            - 10.10.10.1
        networklinks:
            - linuxname: enxda6324c0045d
              hardwareaddress: da:63:24:c0:04:5d
              speedmbps: 1000
              linkup: true
              description: ' '
    lasterror: ""
    managementaddress: fdae:41e4:649b:9303:5ff5:d72c:1142:7b37
    connected: true
    maintenance: true
    cluster: ""
    role: 0
    platformmetadata:
        platform: metal
        hostname: ""
        region: ""
        zone: ""
        instancetype: ""
        instanceid: 65653663-3339-6565-6134-663032613261
        providerid: ""
        spot: false
    imagelabels: {}
    schematic:
        id: ""
        invalid: true

```
