### ISSUE TITLE
[bug] Adding worker node to cluster ignores install path

### ISSUE THREAD

**Issue by fstaffa** [siderolabs/omni#811]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I added zimaboard as a worker node to cluster via UI. I have selected for it to install talos to /dev/mmcblk0 . This setting is ignored and talos was installed to /dev/sda

### Expected Behavior

Talos installs to /dev/mmcblk

### Steps To Reproduce

1. Have new cluster composed of three control planes running talos 1.9.1 and kubernetes 1.32.0 (control plane nodes are running in proxmox)
2. Expand the cluster via UI by adding a zimaboard worker node which booted from usb
3. Select for worker node to install to /dev/mmcblk0

### Anything else?

When I open the node in omni and go to config page, the config page shows following machine configuration, confirming that the install disk was /dev/mmcblk0 :

```yaml
machine:
    type: worker
    token: '******'
    ca:
        crt: [certificate]
        key: ""
    certSANs:
        - [san]
    kubelet:
        image: ghcr.io/siderolabs/kubelet:v1.32.0
        defaultRuntimeSeccompProfileEnabled: true
        disableManifestsDirectory: true
    network:
        hostname: 03000200-0400-0500-0006-000700080009
    install:
        disk: /dev/mmcblk0
        image: factory.talos.dev/installer/5154efdf42a55d7c523370b296c44a9765b6af329848e9e5dd50e851d2fce8a8:v1.9.1
        wipe: true
    features:
        rbac: true
        stableHostname: true
        apidCheckExtKeyUsage: true
        diskQuotaSupport: true
        kubePrism:
            enabled: true
            port: 7445
        hostDNS:
            enabled: true
            forwardKubeDNSToHost: true
```
