### ISSUE TITLE
Omni slowly or not loading when deployed on k8s (Talos) cluster

### ISSUE THREAD

**Issue by thomaspetit** [siderolabs/omni#934]
I've deployed omni on a Talos cluster with 1 CP and 1 worker node. I've used the original helm chart provided with slight modification that shouldn't matter.

There are no issues in running omni on either a docker. However on kubernetes it simply loads incredibly slow. Navigating to the home page, a dropdown box for selecting talos version takes minutes to load.

<img width="632" alt="Image" src="https://github.com/user-attachments/assets/e4940fe6-4ae5-4c3a-8cf1-e5b9f86b2ab8" />

Is there anyone also running omni on Talos succesfully? Prepared to share what I have but at the moment it's a needle in a haystack as I don't get any indication what goes wrong (no error logs or whatsoever). Anybody any idea how I could debug this stuff (how to change the log level of omni, check performance of etcd ,..)

Edit: As further digging into omni has not given any result I can also add that I'm using the Gateway API `HTTPRoute` / `GRPCRoute`. My gut feeling tells me that something weird must be happening on the ingress side as I can't find anything wrong with the rest

```
---
apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: "{{.Release.Name}}-api"
  namespace: {{.Release.Namespace}}
spec:
  parentRefs:
    - name: external-gateway
      namespace: kube-system
  hostnames:
    - omni.example.com
  rules:
    - matches:
        - method:
            service: cosi.resource.state
      backendRefs:
        - name: internal-grpc
          port: 8080
    - matches:
        - method:
            service: management.managementservice
      backendRefs:
        - name: internal-grpc
          port: 8080
    - matches:
        - method:
            service: machine.machineservice
      backendRefs:
        - name: internal-grpc
          port: 8080
    - matches:
        - method:
            service: cluster.clusterservice
      backendRefs:
        - name: internal-grpc
          port: 8080
    - matches:
        - method:
            service: inspect.inspectservice
      backendRefs:
        - name: internal-grpc
          port: 8080
    - matches:
        - method:
            service: resource.resourceservice
      backendRefs:
        - name: internal-grpc
          port: 8080
    - matches:
        - method:
            service: storage.storageservice
      backendRefs:
        - name: internal-grpc
          port: 8080
    - matches:
        - method:
            service: time.timeservice
      backendRefs:
        - name: internal-grpc
          port: 8080
    - matches:
        - method:
            service: auth.authservice
      backendRefs:
        - name: internal-grpc
          port: 8080
    - matches:
        - method:
            service: oicd
      backendRefs:
        - name: internal-grpc
          port: 8080
```

```
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: "{{.Release.Name}}-ui"
  namespace: {{.Release.Namespace}}
spec:
  parentRefs:
    - name: external-gateway
      namespace: kube-system
  hostnames:
    - omni.example.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: internal
          port: 8080
```

```
---
apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: "{{.Release.Name}}-sidero"
  namespace: {{.Release.Namespace}}
spec:
  parentRefs:
    - name: external-gateway
      namespace: kube-system
  hostnames:
    - siderolink.omni.example.com
  rules:
    - backendRefs:
        - group: ''
          kind: Service
          name: internal-grpc
          port: 8090
          weight: 1
      matches:
        - {}
```

```
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: "{{.Release.Name}}-kube"
  namespace: {{.Release.Namespace}}
spec:
  parentRefs:
    - name: external-gateway
      namespace: kube-system
  hostnames:
    - kubernetes.omni.example.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: internal
          port: 8095
```
