### ISSUE TITLE
[bug] Unable to run Omni locally with IPv6 disabled

### ISSUE THREAD

**Issue by kenlasko** [siderolabs/omni#99]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm running Omni on-prem from a Raspberry Pi.  I've been having issues spinning up new Talos clusters. I've noticed that Omni is using some IPv6 addresses in the generated configs, which my network does not fully support. I've been trying to get Omni to function with IPv6 disabled on the node.

I have disabled IPv6 in my test environment by setting ```net.ipv6.conf.all.disable_ipv6 = 1``` in /etc/sysctl.conf. However, Omni refuses to run with this configuration.

```
WRN embed/serve.go:160 > ts=1711984790.9149861 msg=stopping insecure grpc server due to error component=embedded_etcd error=accept tcp 127.0.0.1:2379: use of closed network connection
WRN embed/serve.go:162 > ts=1711984790.915139 msg=stopped insecure grpc server due to error component=embedded_etcd error=accept tcp 127.0.0.1:2379: use of closed network connection
INF etcdserver/server.go:1471 > ts=1711984790.9154017 msg=skipped leadership transfer for single voting member cluster component=embedded_etcd local-member-id=8e9e05c52164694d current-leader-member-id=8e9e05c52164694d
INF embed/etcd.go:579 > ts=1711984790.9279478 msg=stopping serving peer traffic component=embedded_etcd address=127.0.0.1:34377
INF embed/etcd.go:584 > ts=1711984790.9284875 msg=stopped serving peer traffic component=embedded_etcd address=127.0.0.1:34377
INF embed/etcd.go:377 > ts=1711984790.9286697 msg=closed etcd server component=embedded_etcd name=default data-dir=_out/etcd/ advertise-peer-urls=["http://localhost:2380"] advertise-client-urls=["http://localhost:2379"]
Error: failed to run Omni: failed to run server: error initializing wgDevice: error setting address: netlink receive: permission denied
```

### Expected Behavior

Omni is able to run with IPv6 disabled on the node

### Steps To Reproduce

Operating System: Debian GNU/Linux 11 (bullseye)
Kernel: Linux 6.1.21-v8+
Architecture: arm64
Docker 26.0.0

docker-compose.yaml
```
  omni:
    image: ghcr.io/siderolabs/omni:latest
    container_name: omni
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
    command:
      - --account-id=<redacted>
      - --name=onprem-omni
      - --cert=/tls.crt
      - --key=/tls.key
      - --siderolink-api-cert=/tls.crt
      - --siderolink-api-key=/tls.key
      - --private-key-source=file:///omni.asc
      - --event-sink-port=8091
      - --bind-addr=0.0.0.0:4443
      - --siderolink-api-bind-addr=0.0.0.0:8090
      - --k8s-proxy-bind-addr=0.0.0.0:8100
      - --advertised-api-url=https://omni.mydomain.com/
      - --siderolink-api-advertised-url=https://omni.mydomain.com:8090/
      - --siderolink-wireguard-advertised-addr=192.168.1.17:50180
      - --advertised-kubernetes-proxy-url=https://omni.mydomain.com:8100/
      - --auth-auth0-enabled=true
      - --auth-auth0-domain=mydomain.us.auth0.com
      - --auth-auth0-client-id=redacted
      - --initial-users=ken.lasko@mydomain.com
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.omni.rule=Host(`omni.mydomain.com`)"
      - "traefik.http.routers.omni.entrypoints=websecure"
      - "traefik.http.routers.omni.tls=true"
      - "traefik.http.services.omni.loadbalancer.server.port=4443"
      - "traefik.http.services.omni.loadbalancer.server.scheme=https"
    volumes:
      - ./omni/etcd:/_out/etcd
      - ./certs/star_mydomain_com.pem:/tls.crt
      - ./certs/star_mydomain_com.key:/tls.key
      - ./omni/omni.asc:/omni.asc
```

1. Add ```net.ipv6.conf.all.disable_ipv6 = 1``` to /etc/sysctl.conf
2. Reboot node
3. Note error when starting Omni container
4. Remove ```net.ipv6.conf.all.disable_ipv6 = 1``` from /etc/sysctl.conf
5. Reboot node
6. Note successful startup of Omni container

### What browsers are you seeing the problem on?

Chrome
